import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!, SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const supabase=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false}})
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'GET,POST,PUT,OPTIONS','Content-Type':'application/json; charset=utf-8'}
const ok=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:cors}); const fail=(m:string,s=400)=>ok({error:m},s)
async function bj(r:Request){try{return await r.json()}catch{return{}}}
async function au(r:Request){const t=(r.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!t)return null;const{data:s}=await supabase.from('app_sessions').select('user_id').eq('token',t).gt('expires_at',new Date().toISOString()).maybeSingle();if(!s)return null;const{data:u}=await supabase.from('app_users').select('id,username,role,avatar_url,active,vocab').eq('id',s.user_id).eq('active',true).maybeSingle();return u||null}
const strip=(v:any)=>Array.isArray(v)?v.map((x:any)=>{if(!x||typeof x!=='object')return x;const y={...x};delete y.password;return y}):v
function mergeA(old:any,inc:any,n:string){if(!Array.isArray(old))return Array.isArray(inc)?inc:[];if(!Array.isArray(inc))return old;const m=new Map(inc.map((a:any)=>[String(a?.id),a]));return old.map((a:any)=>{const z:any=m.get(String(a?.id));if(!z)return a;const os=a?.subs&&typeof a.subs==='object'?a.subs:{},is=z?.subs&&typeof z.subs==='object'?z.subs:{};return n in is?{...a,subs:{...os,[n]:is[n]}}:a})}
function mergeS(old:any,inc:any,n:string){const o=Array.isArray(old)?old:[],i=Array.isArray(inc)?inc:[],own=i.find((x:any)=>x?.name===n||x?.username===n);if(!own)return strip(o);const c={...own};delete c.password;const k=o.findIndex((x:any)=>x?.name===n||x?.username===n);return k<0?[...strip(o),c]:o.map((x:any,j:number)=>j===k?{...x,...c}:x)}
async function gs(k:string){const{data}=await supabase.from('app_shared_state').select('value').eq('key',k).maybeSingle();return data?.value??null}
async function ps(k:string,v:any){const{error}=await supabase.from('app_shared_state').upsert({key:k,value:v,updated_at:new Date().toISOString()},{onConflict:'key'});if(error)throw error}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});const p=new URL(req.url).pathname.replace(/^.*\/homework-api\/?/,'/');try{
if(p==='/login'&&req.method==='POST'){const b=await bj(req),{data,error}=await supabase.rpc('app_login',{p_username:b.username,p_password:b.password});return error?fail('아이디 또는 비밀번호를 확인해 주세요.',401):ok(data)}
if(p==='/register'&&req.method==='POST'){const b=await bj(req),v=Array.isArray(b.vocab)?b.vocab:[];if(v.some((x:any)=>!x||!['3급','4급','5급','6급'].includes(String(x.level||''))||!Number.isInteger(Number(x.chapter))||Number(x.chapter)<0))return fail('선택한 급수와 시작 과를 확인해 주세요.');const clean=v.map((x:any)=>({level:String(x.level),chapter:Number(x.chapter)}));const{data,error}=await supabase.rpc('app_register_student',{p_username:b.username,p_password:b.password,p_vocab:clean,p_avatar_url:b.avatarUrl||null});if(error){const m=String(error.message||'');if(m.includes('USERNAME_TAKEN'))return fail('이미 사용 중인 이름이에요.',409);if(m.includes('PASSWORD_TOO_SHORT'))return fail('비밀번호는 4자리 이상 입력해 주세요.');return fail('계정 생성에 실패했어요.')}return ok(data,201)}
const u=await au(req);if(!u)return fail('로그인이 필요합니다.',401)
if(p==='/me'&&req.method==='GET')return ok({id:u.id,username:u.username,role:u.role,avatarUrl:u.avatar_url,vocab:u.vocab})
if(p==='/change-password'&&req.method==='POST'){const b=await bj(req),cur=String(b.currentPassword||''),next=String(b.newPassword||'');if(next.length<4)return fail('새 비밀번호는 4자리 이상 입력해 주세요.');const{error}=await supabase.rpc('app_change_password',{p_user_id:u.id,p_current_password:cur,p_new_password:next});if(error){const m=String(error.message||'');if(m.includes('INVALID_CURRENT_PASSWORD'))return fail('현재 비밀번호가 올바르지 않아요.',400);if(m.includes('PASSWORD_TOO_SHORT'))return fail('새 비밀번호는 4자리 이상 입력해 주세요.',400);throw error}return ok({ok:true})}
if(p==='/change-username'&&req.method==='POST'){const b=await bj(req),{data,error}=await supabase.rpc('app_change_username',{p_user_id:u.id,p_new_username:String(b.username||'')});if(error){const m=String(error.message||'');if(m.includes('USERNAME_TAKEN'))return fail('이미 사용 중인 이름이에요.',409);if(m.includes('INVALID_USERNAME'))return fail('이름은 1자 이상 30자 이하로 입력해 주세요.');if(m.includes('RESERVED_USERNAME'))return fail('사용할 수 없는 이름이에요.');throw error}return ok({ok:true,username:data.username})}
if(p==='/state'&&req.method==='GET'){const{data,error}=await supabase.from('app_shared_state').select('key,value,updated_at');if(error)throw error;const state:Record<string,any>={};for(const r of data||[])state[r.key]=r.value;const{data:profiles}=await supabase.from('app_users').select('id,username,avatar_url,active,vocab,created_at').eq('role','student').order('created_at',{ascending:true});return ok({state,profiles:profiles||[]})}
if(p==='/state'&&req.method==='PUT'){const b=await bj(req),k=String(b.key||'');if(!k.startsWith('lin-homework-v3-'))return fail('허용되지 않은 저장 키예요.');let v=b.value,o=await gs(k);if(k.endsWith('-assigns'))v=u.role==='teacher'?v:mergeA(o,v,u.username);else if(k.endsWith('-students'))v=u.role==='teacher'?strip(v):mergeS(o,v,u.username);else if(k.endsWith('-vocab')&&u.role!=='teacher'){const a=o&&typeof o==='object'?o:{},z=v&&typeof v==='object'?v:{};v={...a,[u.username]:z[u.username]??a[u.username]??[]}}else if((k.includes('banner')||k.includes('notice-setting'))&&u.role!=='teacher')return fail('선생님만 공지를 수정할 수 있어요.',403);await ps(k,v);return ok({ok:true,value:v})}
if(p==='/upload-data-url'&&req.method==='POST'){const b=await bj(req),du=String(b.dataUrl||''),m=du.match(/^data:((?:audio|image)\/[a-zA-Z0-9.+-]+);base64,(.+)$/s);if(!m)return fail('파일 형식이 올바르지 않아요.');const mime=m[1],raw=Uint8Array.from(atob(m[2]),c=>c.charCodeAt(0)),isImg=mime.startsWith('image/'),limit=isImg?5*1024*1024:20*1024*1024;if(raw.byteLength>limit)return fail(isImg?'이미지는 5MB 이하만 올릴 수 있어요.':'녹음파일은 20MB 이하만 올릴 수 있어요.',413);const bucket=isImg?'homework-images':'homework-audio',safe=String(b.name||'file').replace(/[^a-zA-Z0-9._-]/g,'_').slice(-100),path=`${u.id}/${Date.now()}-${crypto.randomUUID()}-${safe}`;const{error:e}=await supabase.storage.from(bucket).upload(path,raw,{contentType:mime,upsert:false});if(e)throw e;const{data:s,error:se}=await supabase.storage.from(bucket).createSignedUrl(path,31536000);if(se)throw se;return ok({url:s.signedUrl,path})}
if(p==='/sync-user'&&req.method==='POST'){const b=await bj(req),q:any={updated_at:new Date().toISOString()};if('avatarUrl'in b)q.avatar_url=b.avatarUrl||null;if('vocab'in b)q.vocab=b.vocab||[];const{error}=await supabase.from('app_users').update(q).eq('id',u.id);if(error)throw error;return ok({ok:true})}
if(p==='/student-active'&&req.method==='POST'){if(u.role!=='teacher')return fail('선생님만 변경할 수 있어요.',403);const b=await bj(req),n=String(b.username||''),a=!!b.active;const{error}=await supabase.from('app_users').update({active:a,updated_at:new Date().toISOString()}).eq('username',n).eq('role','student');if(error)throw error;if(!a){const{data:x}=await supabase.from('app_users').select('id').eq('username',n).maybeSingle();if(x?.id)await supabase.from('app_sessions').delete().eq('user_id',x.id)}return ok({ok:true})}
if(p==='/student-vocab'&&req.method==='POST'){if(u.role!=='teacher')return fail('선생님만 변경할 수 있어요.',403);const b=await bj(req),n=String(b.username||''),v=Array.isArray(b.vocab)?b.vocab:[];const{error}=await supabase.from('app_users').update({vocab:v,updated_at:new Date().toISOString()}).eq('username',n).eq('role','student');if(error)throw error;return ok({ok:true})}
return fail('없는 API입니다.',404)}catch(e){console.error(e);return fail('서버 처리 중 오류가 발생했어요.',500)}})
