import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!, SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const supabase=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false}})
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'GET,POST,PUT,OPTIONS','Content-Type':'application/json; charset=utf-8'}
const ok=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:cors}); const fail=(m:string,s=400)=>ok({error:m},s)
async function bj(r:Request){try{return await r.json()}catch{return{}}}
async function au(r:Request){const t=(r.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!t)return null;const{data:s}=await supabase.from('app_sessions').select('user_id').eq('token',t).gt('expires_at',new Date().toISOString()).maybeSingle();if(!s)return null;const{data:u}=await supabase.from('app_users').select('id,username,role,avatar_url,active,vocab').eq('id',s.user_id).eq('active',true).maybeSingle();return u||null}
const staff=(role:string)=>role==='teacher'||role==='admin'
const strip=(v:any)=>Array.isArray(v)?v.map((x:any)=>{if(!x||typeof x!=='object')return x;const y={...x};delete y.password;return y}):v
function mergeA(old:any,inc:any,n:string){if(!Array.isArray(old))return Array.isArray(inc)?inc:[];if(!Array.isArray(inc))return old;const m=new Map(inc.map((a:any)=>[String(a?.id),a]));return old.map((a:any)=>{const z:any=m.get(String(a?.id));if(!z)return a;const os=a?.subs&&typeof a.subs==='object'?a.subs:{},is=z?.subs&&typeof z.subs==='object'?z.subs:{};return n in is?{...a,subs:{...os,[n]:is[n]}}:a})}
function mergeS(old:any,inc:any,n:string){const o=Array.isArray(old)?old:[],i=Array.isArray(inc)?inc:[],own=i.find((x:any)=>x?.name===n||x?.username===n);if(!own)return strip(o);const c={...own};delete c.password;const k=o.findIndex((x:any)=>x?.name===n||x?.username===n);return k<0?[...strip(o),c]:o.map((x:any,j:number)=>j===k?{...x,...c}:x)}
async function gs(k:string){const{data}=await supabase.from('app_shared_state').select('value').eq('key',k).maybeSingle();return data?.value??null}
async function ps(k:string,v:any){const{error}=await supabase.from('app_shared_state').upsert({key:k,value:v,updated_at:new Date().toISOString()},{onConflict:'key'});if(error)throw error}
const uuid=(v:any)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(String(v||''))
const normAnswer=(v:any)=>String(v??'').trim().replace(/\s+/g,'')
async function signed(bucket:string,path:any){if(!path)return null;const{data,error}=await supabase.storage.from(bucket).createSignedUrl(String(path),3600);if(error)throw error;return data.signedUrl}
async function reviewQuestions(setId:string,includeAnswers=false){const{data,error}=await supabase.from('review_questions').select('id,type,prompt,answer,explanation,audio_path,audio_name,position').eq('review_set_id',setId).order('position',{ascending:true});if(error)throw error;return Promise.all((data||[]).map(async(q:any)=>({id:q.id,type:q.type,prompt:q.prompt,...(includeAnswers?{answer:q.answer,explanation:q.explanation}:{}),audioPath:q.audio_path,audioName:q.audio_name,audioUrl:await signed('homework-audio',q.audio_path),position:q.position})))}
async function reviewResult(setId:string,studentId:string){const{data,error}=await supabase.from('review_results').select('answers,correctness,score,total,completed_at').eq('review_set_id',setId).eq('student_id',studentId).maybeSingle();if(error)throw error;return data?{answers:data.answers||{},correctness:data.correctness||{},score:data.score,total:data.total,completedAt:data.completed_at}:null}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});const p=new URL(req.url).pathname.replace(/^.*\/homework-api\/?/,'/');try{
if(p==='/login'&&req.method==='POST'){const b=await bj(req),{data,error}=await supabase.rpc('app_login',{p_username:b.username,p_password:b.password});return error?fail('아이디 또는 비밀번호를 확인해 주세요.',401):ok(data)}
if(p==='/register'&&req.method==='POST'){const b=await bj(req),v=Array.isArray(b.vocab)?b.vocab:[];if(v.some((x:any)=>!x||!['3급','4급','5급','6급'].includes(String(x.level||''))||!Number.isInteger(Number(x.chapter))||Number(x.chapter)<0))return fail('선택한 급수와 시작 과를 확인해 주세요.');const clean=v.map((x:any)=>({level:String(x.level),chapter:Number(x.chapter)}));const{data,error}=await supabase.rpc('app_register_student',{p_username:b.username,p_password:b.password,p_vocab:clean,p_avatar_url:b.avatarUrl||null});if(error){const m=String(error.message||'');if(m.includes('USERNAME_TAKEN'))return fail('이미 사용 중인 이름이에요.',409);if(m.includes('PASSWORD_TOO_SHORT'))return fail('비밀번호는 4자리 이상 입력해 주세요.');return fail('계정 생성에 실패했어요.')}return ok(data,201)}
const u=await au(req);if(!u)return fail('로그인이 필요합니다.',401)
if(p.startsWith('/admin/')){
if(u.role!=='admin')return fail('관리자만 사용할 수 있어요.',403)
if(p==='/admin/accounts'&&req.method==='GET'){const{data,error}=await supabase.from('app_users').select('id,username,role,active').in('role',['teacher','student']).order('created_at',{ascending:true});if(error)throw error;return ok({accounts:data||[]})}
if(p==='/admin/reset-password'&&req.method==='POST'){const b=await bj(req);if(typeof b.userId!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(b.userId))return fail('계정을 확인해 주세요.');const{error}=await supabase.rpc('app_admin_reset_password',{p_admin_id:u.id,p_user_id:b.userId});if(error){const m=String(error.message||'');if(m.includes('ADMIN_REQUIRED'))return fail('관리자만 사용할 수 있어요.',403);if(m.includes('ACCOUNT_NOT_FOUND'))return fail('초기화할 계정을 찾을 수 없어요.',404);throw error}return ok({ok:true})}
if(p==='/admin/reviews'&&req.method==='GET'){const{data:sets,error}=await supabase.from('review_sets').select('id,lesson_date,title,status,source_image_paths,created_at,updated_at,published_at').order('lesson_date',{ascending:false});if(error)throw error;const items=[];for(const set of sets||[]){const questions=await reviewQuestions(set.id,true),sourceImages=[];for(const path of set.source_image_paths||[])sourceImages.push({path,url:await signed('homework-images',path)});items.push({id:set.id,lessonDate:set.lesson_date,title:set.title,status:set.status,sourceImages,questions,createdAt:set.created_at,updatedAt:set.updated_at,publishedAt:set.published_at})}return ok({reviews:items})}
if(p==='/admin/reviews/save'&&req.method==='POST'){const b=await bj(req),{data,error}=await supabase.rpc('app_admin_save_review_set',{p_admin_id:u.id,p_payload:b});if(error){const m=String(error.message||'');if(m.includes('ADMIN_REQUIRED'))return fail('관리자만 사용할 수 있어요.',403);if(m.includes('LESSON_DATE_REQUIRED'))return fail('수업 날짜를 입력해 주세요.');if(m.includes('INVALID_REVIEW_QUESTIONS')||m.includes('QUESTION_FIELDS_REQUIRED'))return fail('문제와 정답을 모두 입력해 주세요.');if(m.includes('INVALID_QUESTION_TYPE'))return fail('문제 유형을 확인해 주세요.');throw error}return ok({ok:true,id:data})}
if(p==='/admin/review-source-upload'&&req.method==='POST'){const b=await bj(req),du=String(b.dataUrl||''),m=du.match(/^data:(image\/[a-zA-Z0-9.+-]+);base64,(.+)$/s);if(!m)return fail('이미지 형식이 올바르지 않아요.');const raw=Uint8Array.from(atob(m[2]),c=>c.charCodeAt(0));if(raw.byteLength>5*1024*1024)return fail('이미지는 5MB 이하만 올릴 수 있어요.',413);const safe=String(b.name||'review.webp').replace(/[^a-zA-Z0-9._-]/g,'_').slice(-100),path=`reviews/${u.id}/${Date.now()}-${crypto.randomUUID()}-${safe}`;const{error:e}=await supabase.storage.from('homework-images').upload(path,raw,{contentType:m[1],upsert:false});if(e)throw e;return ok({path,url:await signed('homework-images',path)})}
return fail('없는 API입니다.',404)
}
if(p==='/me'&&req.method==='GET')return ok({id:u.id,username:u.username,role:u.role,avatarUrl:u.avatar_url,vocab:u.vocab})
if(p==='/change-password'&&req.method==='POST'){const b=await bj(req),cur=String(b.currentPassword||''),next=String(b.newPassword||'');if(next.length<4)return fail('새 비밀번호는 4자리 이상 입력해 주세요.');const{error}=await supabase.rpc('app_change_password',{p_user_id:u.id,p_current_password:cur,p_new_password:next});if(error){const m=String(error.message||'');if(m.includes('INVALID_CURRENT_PASSWORD'))return fail('현재 비밀번호가 올바르지 않아요.',400);if(m.includes('PASSWORD_TOO_SHORT'))return fail('새 비밀번호는 4자리 이상 입력해 주세요.',400);throw error}return ok({ok:true})}
if(p==='/change-username'&&req.method==='POST'){const b=await bj(req),{data,error}=await supabase.rpc('app_change_username',{p_user_id:u.id,p_new_username:String(b.username||'')});if(error){const m=String(error.message||'');if(m.includes('USERNAME_TAKEN'))return fail('이미 사용 중인 이름이에요.',409);if(m.includes('INVALID_USERNAME'))return fail('이름은 1자 이상 30자 이하로 입력해 주세요.');if(m.includes('RESERVED_USERNAME'))return fail('사용할 수 없는 이름이에요.');throw error}return ok({ok:true,username:data.username})}
if(p==='/state'&&req.method==='GET'){const{data,error}=await supabase.from('app_shared_state').select('key,value,updated_at');if(error)throw error;const state:Record<string,any>={};for(const r of data||[])state[r.key]=r.value;const{data:profiles}=await supabase.from('app_users').select('id,username,avatar_url,active,vocab,created_at').eq('role','student').order('created_at',{ascending:true});return ok({state,profiles:profiles||[]})}
if(p==='/state'&&req.method==='PUT'){const b=await bj(req),k=String(b.key||'');if(!k.startsWith('lin-homework-v3-'))return fail('허용되지 않은 저장 키예요.');let v=b.value,o=await gs(k);if(k.endsWith('-assigns'))v=staff(u.role)?v:mergeA(o,v,u.username);else if(k.endsWith('-students'))v=staff(u.role)?strip(v):mergeS(o,v,u.username);else if(k.endsWith('-vocab')&&!staff(u.role)){const a=o&&typeof o==='object'?o:{},z=v&&typeof v==='object'?v:{};v={...a,[u.username]:z[u.username]??a[u.username]??[]}}else if((k.includes('banner')||k.includes('notice-setting'))&&!staff(u.role))return fail('선생님만 공지를 수정할 수 있어요.',403);await ps(k,v);return ok({ok:true,value:v})}
if(p==='/upload-data-url'&&req.method==='POST'){const b=await bj(req),du=String(b.dataUrl||''),m=du.match(/^data:((?:audio|image)\/[a-zA-Z0-9.+-]+);base64,(.+)$/s);if(!m)return fail('파일 형식이 올바르지 않아요.');const mime=m[1],raw=Uint8Array.from(atob(m[2]),c=>c.charCodeAt(0)),isImg=mime.startsWith('image/'),limit=isImg?5*1024*1024:20*1024*1024;if(raw.byteLength>limit)return fail(isImg?'이미지는 5MB 이하만 올릴 수 있어요.':'녹음파일은 20MB 이하만 올릴 수 있어요.',413);const bucket=isImg?'homework-images':'homework-audio',safe=String(b.name||'file').replace(/[^a-zA-Z0-9._-]/g,'_').slice(-100),path=`${u.id}/${Date.now()}-${crypto.randomUUID()}-${safe}`;const{error:e}=await supabase.storage.from(bucket).upload(path,raw,{contentType:mime,upsert:false});if(e)throw e;const{data:s,error:se}=await supabase.storage.from(bucket).createSignedUrl(path,31536000);if(se)throw se;return ok({url:s.signedUrl,path})}
if(p==='/reviews'&&req.method==='GET'){const{data:sets,error}=await supabase.from('review_sets').select('id,lesson_date,title').eq('status','published').order('lesson_date',{ascending:false});if(error)throw error;let results:any[]=[];if(u.role==='student'&&(sets||[]).length){const r=await supabase.from('review_results').select('review_set_id,score,total,completed_at').eq('student_id',u.id).in('review_set_id',(sets||[]).map((x:any)=>x.id));if(r.error)throw r.error;results=r.data||[]}const bySet=new Map(results.map((r:any)=>[r.review_set_id,r]));return ok({reviews:(sets||[]).map((set:any)=>{const r:any=bySet.get(set.id);return{id:set.id,lessonDate:set.lesson_date,title:set.title,completed:!!r,score:r?.score??null,total:r?.total??null,completedAt:r?.completed_at??null}})})}
const reviewMatch=p.match(/^\/reviews\/([0-9a-f-]+)$/i)
if(reviewMatch&&req.method==='GET'){const setId=reviewMatch[1];if(!uuid(setId))return fail('복습을 찾을 수 없어요.',404);let q=supabase.from('review_sets').select('id,lesson_date,title,status').eq('id',setId);if(u.role==='student')q=q.eq('status','published');const{data:set,error}=await q.maybeSingle();if(error)throw error;if(!set)return fail('복습을 찾을 수 없어요.',404);const result=u.role==='student'?await reviewResult(setId,u.id):null,questions=await reviewQuestions(setId,!!result||u.role==='admin');return ok({review:{id:set.id,lessonDate:set.lesson_date,title:set.title,status:set.status,questions,result}})}
const submitMatch=p.match(/^\/reviews\/([0-9a-f-]+)\/submit$/i)
if(submitMatch&&req.method==='POST'){if(u.role!=='student')return fail('학생만 제출할 수 있어요.',403);const setId=submitMatch[1];if(!uuid(setId))return fail('복습을 찾을 수 없어요.',404);const existing=await reviewResult(setId,u.id);if(existing){const questions=await reviewQuestions(setId,true);return ok({result:existing,questions})}const{data:set,error:setError}=await supabase.from('review_sets').select('id').eq('id',setId).eq('status','published').maybeSingle();if(setError)throw setError;if(!set)return fail('복습을 찾을 수 없어요.',404);const questions=await reviewQuestions(setId,true);if(!questions.length)return fail('등록된 문제가 없어요.');const b=await bj(req),raw=b.answers&&typeof b.answers==='object'?b.answers:{},answers:Record<string,string>={},correctness:Record<string,boolean>={};let score=0;for(const question of questions){const answer=String(raw[question.id]??'');answers[question.id]=answer;const correct=normAnswer(answer)===normAnswer(question.answer);correctness[question.id]=correct;if(correct)score++}const row={review_set_id:setId,student_id:u.id,answers,correctness,score,total:questions.length},{error}=await supabase.from('review_results').insert(row);if(error){if(String(error.code)==='23505'){const result=await reviewResult(setId,u.id);return ok({result,questions})}throw error}return ok({result:{answers,correctness,score,total:questions.length,completedAt:new Date().toISOString()},questions},201)}
if(p==='/sync-user'&&req.method==='POST'){const b=await bj(req),q:any={updated_at:new Date().toISOString()};if('avatarUrl'in b)q.avatar_url=b.avatarUrl||null;if('vocab'in b)q.vocab=b.vocab||[];const{error}=await supabase.from('app_users').update(q).eq('id',u.id);if(error)throw error;return ok({ok:true})}
if(p==='/student-active'&&req.method==='POST'){if(!staff(u.role))return fail('선생님만 변경할 수 있어요.',403);const b=await bj(req),n=String(b.username||''),a=!!b.active;const{error}=await supabase.from('app_users').update({active:a,updated_at:new Date().toISOString()}).eq('username',n).eq('role','student');if(error)throw error;if(!a){const{data:x}=await supabase.from('app_users').select('id').eq('username',n).maybeSingle();if(x?.id)await supabase.from('app_sessions').delete().eq('user_id',x.id)}return ok({ok:true})}
if(p==='/student-vocab'&&req.method==='POST'){if(!staff(u.role))return fail('선생님만 변경할 수 있어요.',403);const b=await bj(req),n=String(b.username||''),v=Array.isArray(b.vocab)?b.vocab:[];const{error}=await supabase.from('app_users').update({vocab:v,updated_at:new Date().toISOString()}).eq('username',n).eq('role','student');if(error)throw error;return ok({ok:true})}
return fail('없는 API입니다.',404)}catch(e){console.error(e);return fail('서버 처리 중 오류가 발생했어요.',500)}})
